aadhaar:
  front:
    full_name:
      regex: '(?i)^[A-Z][a-z]+ [A-Z][a-z]+$'
      lines_after: 2   # how many lines after "Government of India" to look at
    dob:
      regex: '\d{2}/\d{2}/\d{4}'
    gender:
      regex: '(MALE|FEMALE|पुरुष|स्त्री)'
    aadhaar_number:
      regex: '\b\d{4}\s?\d{4}\s?\d{4}\b'
  back:
    address:
      start_patterns:
        - 'Address'
        - 'The Nest'
        - 'House No'
        - 'Flat No'
      stop_patterns:
        - '^\s*$'           # blank line
        - '\d{4}\s?\d{4}\s?\d{4}' # aadhaar number
        - 'help@uidai'
        - 'www.uidai'
        - 'VID'
      max_lines: 7
